version: '2'
services:
  web:
    container_name: "mozerpol-server"
    build: .
    env_file: ".env"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "${DATABASE_DIR}:${DATABASE_DIR}"
    restart: 'unless-stopped'
